#!/usr/bin/env bash
# tinted-tuicr generate.sh  —  Generate tuicr UI theme + syntax theme from
# Tinty environment variables (Tinty ≥ 0.29).
#
# Reads the current scheme's palette via $TINTY_SCHEME_PALETTE_BASE{*}_HEX_*
# env vars, maps base16 colours to tuicr's ~42 UI keys and writes a
# ~/.config/tuicr/themes/tinted.toml. Also generates a matching TextMate
# .tmTheme for syntax highlighting inside diffs.
#
# Usage:
#   Directly:  ./scripts/generate.sh
#   Via tinty: hook = "bash ~/.local/share/tinted-theming/tinty/repos/tinted-tuicr/scripts/generate.sh"

set -euo pipefail

# ── Configuration ──────────────────────────────────────────────────────────
TUICR_THEMES="${HOME}/.config/tuicr/themes"
TUICR_TOML="${TUICR_THEMES}/tinted.toml"
TUICR_TMTHEME="${TUICR_THEMES}/tinted.tmTheme"

# ── Helpers ────────────────────────────────────────────────────────────────

# Build a full #RRGGBB hex colour from individual TINTY_SCHEME_PALETTE env vars.
# Usage: get_hex "BASE00"  →  "#171e1f"
get_hex() {
  local prefix="$1"
  local var_r="TINTY_SCHEME_PALETTE_${prefix}_HEX_R"
  local var_g="TINTY_SCHEME_PALETTE_${prefix}_HEX_G"
  local var_b="TINTY_SCHEME_PALETTE_${prefix}_HEX_B"
  local r="${!var_r:-00}"
  local g="${!var_g:-00}"
  local b="${!var_b:-00}"
  printf "#%s%s%s" "$r" "$g" "$b"
}

# Blend two #RRGGBB colours: blend $base $accent $pct
# pct=0 → 100% base; pct=100 → 100% accent
blend() {
  local base="$1" accent="$2" pct="$3"
  local br=$((16#${base:1:2}))
  local bg=$((16#${base:3:2}))
  local bb=$((16#${base:5:2}))
  local ar=$((16#${accent:1:2}))
  local ag=$((16#${accent:3:2}))
  local ab=$((16#${accent:5:2}))
  local inv=$((100 - pct))
  local r=$(( (br * inv + ar * pct) / 100 ))
  local g=$(( (bg * inv + ag * pct) / 100 ))
  local b=$(( (bb * inv + ab * pct) / 100 ))
  printf "#%02x%02x%02x" "$r" "$g" "$b"
}

# Determine if a hex colour is dark (avg < 128)
is_dark() {
  local hex="$1"
  local r=$((16#${hex:1:2}))
  local g=$((16#${hex:3:2}))
  local b=$((16#${hex:5:2}))
  local avg=$(( (r + g + b) / 3 ))
  [ "$avg" -lt 128 ]
}

# ── Step 1 — extract palette from env vars ─────────────────────────────────
# Verify we have at least base00 (background) — the most critical colour.
if [ -z "${TINTY_SCHEME_PALETTE_BASE00_HEX_R:-}" ]; then
  echo "[tinted-tuicr] ERROR: TINTY_SCHEME_PALETTE_* env vars not set." >&2
  echo "[tinted-tuicr]        This script requires Tinty ≥ 0.29 to run." >&2
  exit 1
fi

SCHEME_SLUG="${TINTY_SCHEME_SLUG:-unknown}"
SCHEME_SYSTEM="${TINTY_SCHEME_SYSTEM:-base16}"
SCHEME_FULL="${SCHEME_SYSTEM}-${SCHEME_SLUG}"
VARIANT="${TINTY_SCHEME_VARIANT:-dark}"

b00="$(get_hex "BASE00")"
b01="$(get_hex "BASE01")"
b02="$(get_hex "BASE02")"
b03="$(get_hex "BASE03")"
b04="$(get_hex "BASE04")"
b05="$(get_hex "BASE05")"
b06="$(get_hex "BASE06")"
b07="$(get_hex "BASE07")"
b08="$(get_hex "BASE08")"
b09="$(get_hex "BASE09")"
b0A="$(get_hex "BASE0A")"
b0B="$(get_hex "BASE0B")"
b0C="$(get_hex "BASE0C")"
b0D="$(get_hex "BASE0D")"
b0E="$(get_hex "BASE0E")"
b0F="$(get_hex "BASE0F")"

echo "[tinted-tuicr] scheme: $SCHEME_FULL  variant: $VARIANT" >&2

# ── Step 2 — derive blended/computed colours ───────────────────────────────
diff_add_bg="$(blend "$b00" "$b0B" 20)"
diff_del_bg="$(blend "$b00" "$b08" 20)"
syntax_add_bg="$(blend "$b00" "$b0B" 16)"
syntax_del_bg="$(blend "$b00" "$b08" 16)"

# Accent foreground for message/mode badges. Dark panels use base00 for
# contrast on bright badges; light panels use base07.
if is_dark "$b00"; then
  accent_fg="$b00"
else
  accent_fg="$b07"
fi

# ── Step 3 — write tuicr UI theme TOML ────────────────────────────────────
mkdir -p "$TUICR_THEMES"

cat > "$TUICR_TOML" << TUICR_EOF
# tuicr local theme generated by tinted-tuicr
# Scheme: ${SCHEME_FULL}  Variant: ${VARIANT}

# Base colours
panel_bg = "${b00}"
bg_highlight = "${b01}"
fg_primary = "${b05}"
fg_secondary = "${b04}"
fg_dim = "${b03}"

# Diff colours
diff_add = "${b0B}"
diff_add_bg = "${diff_add_bg}"
diff_del = "${b08}"
diff_del_bg = "${diff_del_bg}"
diff_context = "${b05}"
diff_hunk_header = "${b0D}"
expanded_context_fg = "${b03}"

# Syntax highlight diff backgrounds
syntax_add_bg = "${syntax_add_bg}"
syntax_del_bg = "${syntax_del_bg}"

# Syntax theme for code highlighting inside diffs
syntax_theme = "tinted.tmTheme"

# File status
file_added = "${b0B}"
file_modified = "${b0A}"
file_deleted = "${b08}"
file_renamed = "${b0E}"

# Review status
reviewed = "${b0B}"
pending = "${b0A}"

# Comment types
comment_note = "${b0D}"
comment_suggestion = "${b0C}"
comment_issue = "${b08}"
comment_praise = "${b0B}"

# UI elements
border_focused = "${b0C}"
border_unfocused = "${b02}"
status_bar_bg = "${b01}"
cursor_color = "${b09}"
cursor_line_bg = "${b01}"
branch_name = "${b0C}"
help_indicator = "${b03}"

# Message badges
message_info_fg = "${accent_fg}"
message_info_bg = "${b0D}"
message_warning_fg = "${accent_fg}"
message_warning_bg = "${b0A}"
message_error_fg = "${accent_fg}"
message_error_bg = "${b08}"

# Update badge
update_badge_fg = "${accent_fg}"
update_badge_bg = "${b09}"

# Mode indicator
mode_fg = "${accent_fg}"
mode_bg = "${b0D}"
TUICR_EOF

# ── Step 4 — write syntax .tmTheme ────────────────────────────────────────
cat > "$TUICR_TMTHEME" << TM_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>tinted-tuicr (${SCHEME_FULL})</string>
  <key>uuid</key>
  <string>$(uuidgen)</string>
  <key>settings</key>
  <array>
    <dict>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b05}</string>
        <key>background</key>
        <string>${b00}</string>
        <key>caret</key>
        <string>${b05}</string>
        <key>selection</key>
        <string>${b02}</string>
        <key>lineHighlight</key>
        <string>${b01}</string>
        <key>invisibles</key>
        <string>${b03}</string>
        <key>gutter</key>
        <string>${b03}</string>
        <key>gutterForeground</key>
        <string>${b04}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Comment</string>
      <key>scope</key>
      <string>comment, punctuation.definition.comment</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b03}</string>
        <key>fontStyle</key>
        <string>italic</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Keyword</string>
      <key>scope</key>
      <string>keyword, storage, storage.type, storage.modifier</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b0E}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>String</string>
      <key>scope</key>
      <string>string, string constant.character.escape, punctuation.definition.string</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b0B}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Constant</string>
      <key>scope</key>
      <string>constant, constant.numeric, constant.language, constant.character</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b09}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Function / Type</string>
      <key>scope</key>
      <string>entity.name.function, support.function, entity.name.type, support.type</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b0D}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Variable</string>
      <key>scope</key>
      <string>variable, variable.parameter, variable.other, support.variable</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b05}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Support / Tag / Operator</string>
      <key>scope</key>
      <string>support, support.class, support.constant, entity.name.tag, meta.tag, punctuation.definition.tag, punctuation.separator.key-value, keyword.operator, constant.other.symbol</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b0C}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Class / Markup Bold</string>
      <key>scope</key>
      <string>entity.name.class, entity.name.module, markup.bold</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b0A}</string>
        <key>fontStyle</key>
        <string>bold</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Tag / Attribute / Heading</string>
      <key>scope</key>
      <string>entity.name.tag, entity.other.attribute-name, markup.heading</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b08}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Deprecated</string>
      <key>scope</key>
      <string>invalid.deprecated</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b0F}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Invalid</string>
      <key>scope</key>
      <string>invalid, invalid.illegal</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b00}</string>
        <key>background</key>
        <string>${b08}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Diff Inserted</string>
      <key>scope</key>
      <string>markup.inserted, markup.inserted.diff</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b0B}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Diff Deleted</string>
      <key>scope</key>
      <string>markup.deleted, markup.deleted.diff</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b08}</string>
      </dict>
    </dict>
    <dict>
      <key>name</key>
      <string>Diff Changed</string>
      <key>scope</key>
      <string>markup.changed, markup.changed.diff</string>
      <key>settings</key>
      <dict>
        <key>foreground</key>
        <string>${b0E}</string>
      </dict>
    </dict>
  </array>
</dict>
</plist>
TM_EOF

echo "[tinted-tuicr] wrote tuicr theme  → $TUICR_TOML" >&2
echo "[tinted-tuicr] wrote syntax theme → $TUICR_TMTHEME" >&2
echo "[tinted-tuicr] done." >&2
